version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_php73
    image: gangbo/php73
    #container_name: app
    restart: unless-stopped
    tty: true
    environment:
      APP_NAME: xyf-app-api
      YII_ENV: dev
      YII_DEBUG: 1
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/cron.d/app.cron:/etc/cron.d/app.cron
    ports:
      - "8880:80"
