FROM php:7.3-fpm
# Set working directory
WORKDIR /var/www
# Install dependencies
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
        build-essential \
        libpng-dev \
        libmcrypt-dev \
        libzip-dev \
        libjpeg62-turbo-dev \
        libfreetype6-dev \
        locales \
        zip \
        jpegoptim optipng pngquant gifsicle \
        vim \
        unzip \
        curl \
        nginx \
        procps \
        cron
# Clear cache
#RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy existing application directory contents
COPY . /var/www
# Install extensions
RUN docker-php-ext-install pdo_mysql zip exif pcntl bcmath \
    && docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ \
    && docker-php-ext-install gd

RUN pecl install mcrypt \
    && echo 'extension=mcrypt.so' >  /usr/local/etc/php/conf.d/php-ext-mcrypt.ini \
    && pecl install /var/www/docker/redis-5.3.1.tgz \
    && echo 'extension=redis.so' >  /usr/local/etc/php/conf.d/php-ext-redis.ini


RUN cp /var/www/docker/composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# Add user for laravel application
RUN groupadd -g 1000 www \
    && useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
#USER www
# Expose port 9000 and start php-fpm server
EXPOSE 80
CMD ["bash", "/var/www/docker/run.sh"]
